apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  selector: 
    app: prometheus-deployment
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 9090 
